.PHONY: clean All

All:
	@echo "----------Building project:[ Question7Quiz - Debug ]----------"
	@cd "Question7Quiz" && "$(MAKE)" -f  "Question7Quiz.mk"
clean:
	@echo "----------Cleaning project:[ Question7Quiz - Debug ]----------"
	@cd "Question7Quiz" && "$(MAKE)" -f  "Question7Quiz.mk" clean
