// Section 8 - Converting EUR to USD

#include <iostream>

using namespace std;

int main() {
    
    // conversion value init as constant
    const double usd_per_eur {1.19};
    
    cout << "Welcome to the EUR to USD converter" << endl;
    cout << "Enter the value in EUR: ";
    
    double euros {0.0};
    double dollars {0.0};
    
    cin >> euros;
    dollars = euros * usd_per_eur;
    
    cout << euros << " EUR is equivalent to " << dollars << " dollars" << endl; 
    
    cout << endl; // separates time message generated by compiler
    return 0;
}