.PHONY: clean All

All:
	@echo "----------Building project:[ FavoriteNumberChallenge - Debug ]----------"
	@cd "FavoriteNumberChallenge" && "$(MAKE)" -f  "FavoriteNumberChallenge.mk"
clean:
	@echo "----------Cleaning project:[ FavoriteNumberChallenge - Debug ]----------"
	@cd "FavoriteNumberChallenge" && "$(MAKE)" -f  "FavoriteNumberChallenge.mk" clean
